on: [push]

jobs:
  testactions_job:
    runs-on: ubuntu-latest
    name: Ext FS issue on qemued arms
    steps:
    - name: Run some commands on armv7
      id: runcmd
      uses: uraimo/run-on-arch-action@master
      with:
        architecture: armv7
        distribution: ubuntu18.04
        run: |
          apt update
          apt install -y build-essential curl git wget
          uname -a
          echo | gcc -v -E - 2>&1 | grep cc1
          lscpu | grep "Model name:" | sed -r 's/Model name:\s{1,}//g'
          cat /proc/meminfo | grep MemTotal | sed -r 's/MemTotal:\s{1,}//g'
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH=$PATH:$HOME/.cargo/bin
          git clone https://github.com/Y2Z/monolith.git
          cd monolith
          make install
